### ISSUE TITLE
QoL milestone

### ISSUE THREAD

**Issue by kanadgupta** [kanadgupta/mn-poll-finder#1]
- [x] Vitest (see #2)
- [x] TypeScript (see https://github.com/kanadgupta/mn-precinct-finder/pull/3)
- [x] Move to hono? (see https://github.com/kanadgupta/mn-precinct-finder/pull/4)
- [x] React? Or some other not-terrible templating engine? (see https://github.com/kanadgupta/mn-precinct-finder/pull/4)
- [ ] Move off of Google Maps over to [Nominatim](https://nominatim.org/release-docs/latest/api/Overview/)
- [x] Move off Glitch ([c'mon y'all!](https://help.glitch.com/s/article/What-version-of-Node-can-I-use-and-how-do-I-change-update-upgrade-it))
- [ ] Identify + remove cruft (e.g., do we need a separate Deno-runtime-based script? do we need Glitch assets?)
